# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.10
  working_directory: ~/repo

jobs:
  visual:
    docker:
      - image: circleci/ruby:2.6.2-node-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            yarn install
            yarn global add serve
            gem install percy-cli
      - run:
          name: Run visual test
          command: |
            yarn build
            serve -s build
            percy snapshot build

workflows:
  version: 2
  test:
    jobs:
      - visual
